package session

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// WriteHandoff writes a structured handoff.md to path.
// irHash is the current IR root_hash (short form, may be empty).
// irDiff is the output of `ai-ir diff --since=session-start --compact` (may be empty).
// summary may be nil (factual-only mode).
func WriteHandoff(path string, fact *Fact, summary *Summary, irDiff, irHash string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := func(format string, args ...interface{}) {
		fmt.Fprintf(f, format, args...)
	}

	date := fact.EndTime.UTC().Format("2006-01-02")
	if fact.EndTime.IsZero() {
		date = time.Now().UTC().Format("2006-01-02")
	}
	model := fact.Model
	if model == "" {
		model = "unknown"
	}
	cost := CostEstimate(fact)

	// Build front-matter values.
	allFiles := append(append([]string{}, fact.FilesCreated...), fact.FilesEdited...)
	allFiles = sorted(allFiles)
	filesJSON := toJSONStringArray(allFiles)

	nextIntent := ""
	if summary != nil && len(summary.NextSteps) > 0 {
		nextIntent = summary.NextSteps[0]
	}
	if nextIntent == "" {
		nextIntent = "Review changes and continue next planned task"
	}
	// Escape YAML single-quote by doubling; wrap in single quotes for safety.
	nextIntentYAML := "'" + strings.ReplaceAll(nextIntent, "'", "''") + "'"

	// Write YAML front-matter.
	w("---\n")
	w("session_id: %q\n", fact.SessionID)
	w("ir_hash: %q\n", irHash)
	w("status: clean\n")
	w("tasks_touched: []\n")
	w("files_changed: %s\n", filesJSON)
	w("next_session_intent: %s\n", nextIntentYAML)
	w("---\n\n")

	w("# Session Handoff\n")
	w("**Date:** %s | **Turns:** %d | **Duration:** %s | **Cost:** ~$%.2f\n",
		date, fact.TurnCount, FormatDuration(fact.TotalDurationMs), cost)
	w("**Model:** %s | **Tokens:** %dk in / %dk out / %dk cache\n\n",
		model, fact.InputTokens/1000, fact.OutputTokens/1000, fact.CacheReads/1000)

	if len(fact.FilesEdited) > 0 || len(fact.FilesCreated) > 0 {
		w("## Files Changed\n")
		edited := sorted(fact.FilesEdited)
		created := sorted(fact.FilesCreated)
		for _, p := range created {
			w("- %s (created)\n", shortPath(p))
		}
		for _, p := range edited {
			w("- %s (edited)\n", shortPath(p))
		}
		w("\n")
	}

	if len(fact.Commands) > 0 {
		w("## Commands Run\n")
		for _, cmd := range fact.Commands {
			w("- %s\n", cmd)
		}
		w("\n")
	}

	if irDiff != "" {
		w("## Structural Changes\n")
		w("%s\n\n", irDiff)
	}

	if summary != nil {
		if len(summary.Accomplished) > 0 {
			w("## Accomplished\n")
			for _, item := range summary.Accomplished {
				w("- %s\n", item)
			}
			w("\n")
		}
		if len(summary.Decisions) > 0 {
			w("## Decisions\n")
			for _, item := range summary.Decisions {
				w("- %s\n", item)
			}
			w("\n")
		}
		if len(summary.Open) > 0 {
			w("## In Progress\n")
			for _, item := range summary.Open {
				w("- %s\n", item)
			}
			w("\n")
		}
		if len(summary.NextSteps) > 0 {
			w("## Next Steps\n")
			for i, item := range summary.NextSteps {
				w("%d. %s\n", i+1, item)
			}
			w("\n")
		}
	} else {
		w("## Accomplished\n")
		w("- (factual-only mode — set RUNECHO_CLASSIFIER_KEY for narrative summary)\n")
		w("- See Files Changed and Commands Run above for ground-truth activity\n\n")
		w("## Next Steps\n")
		w("1. Review git log for changes made this session\n")
		w("2. Re-orient with IR context on next session start\n\n")
	}

	w("## Notes\n")
	w("- Generated by ai-session from Claude Code JSONL session log\n")

	return nil
}

// toJSONStringArray renders a []string as a compact JSON array literal.
func toJSONStringArray(ss []string) string {
	if len(ss) == 0 {
		return "[]"
	}
	var sb strings.Builder
	sb.WriteByte('[')
	for i, s := range ss {
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteByte('"')
		sb.WriteString(strings.ReplaceAll(s, `"`, `\"`))
		sb.WriteByte('"')
	}
	sb.WriteByte(']')
	return sb.String()
}

func sorted(ss []string) []string {
	out := make([]string, len(ss))
	copy(out, ss)
	sort.Strings(out)
	return out
}

// shortPath returns the last 3 path components for readable output.
func shortPath(p string) string {
	p = strings.ReplaceAll(p, "\\", "/")
	parts := strings.Split(p, "/")
	if len(parts) <= 3 {
		return p
	}
	return strings.Join(parts[len(parts)-3:], "/")
}
