// Package bench is the synthetic hallucination-reduction benchmark for the
// RunEcho guard. It scores guard.Run as a binary classifier over symbol
// references: a reference to a symbol that does not exist is a "hallucination"
// the guard should flag; a reference to a real symbol should pass untouched.
//
// The corpus is generated by perturbing declared symbol pools with a seeded
// RNG, so the same seed yields the same cases — a deterministic benchmark for a
// determinism tool. It measures ONE thing: the guard's ref-extraction +
// validation classifier. The known-symbol set is supplied directly (not derived
// from the IR), so IR extraction accuracy — a separate claim — is held constant
// and does not contaminate the score.
//
// What this does NOT measure: a real LLM error distribution. Synthetic
// perturbations approximate the shape of model mistakes (typos, plausible-absent
// helpers, renamed-away symbols) but are authored, not observed. The captured-
// LLM corpus (Phase 2) supplies that external signal; this scaffold supplies the
// in-CI number and the parser-regression guard.
package bench

import (
	"math/rand"
	"sort"

	"github.com/inth3shadows/runecho/internal/guard"
)

// Label marks whether a case's referenced symbol should be flagged by the guard.
type Label int

const (
	// Real: the referenced symbol exists in the known set; the guard should NOT
	// flag it. A flag here is a false positive (the adoption-killer metric).
	Real Label = iota
	// Hallucinated: the referenced symbol does not exist; the guard SHOULD flag
	// it. A miss here is a false negative (a hallucination that slips through).
	Hallucinated
)

// Category names the kind of perturbation (or "real" for negatives), so the
// scorecard can break catch-rate down by hallucination shape.
type Category string

const (
	CatReal           Category = "real"            // negative: a symbol that exists
	CatTypo           Category = "typo"            // single-edit slip: parseConfig -> parseConfg
	CatPlausibleAffix Category = "plausible_affix" // parseConfig -> parseConfigFile / loadParseConfig
	CatWrongCase      Category = "wrong_case"      // parseConfig -> ParseConfig
	CatInvented       Category = "invented"        // a wholly invented plausible helper
	CatRenamedAway    Category = "renamed_away"    // an old-looking name when the new one exists
)

// Case is one labeled reference: a single line of source that calls Symbol,
// classified against Known.
type Case struct {
	Lang     guard.Lang
	Path     string   // synthetic path, drives LangFor (e.g. "synthetic.go")
	Line     string   // source line placing Symbol in a call position
	Symbol   string   // the referenced callee
	Known    []string // the symbol universe for this language (sorted, deterministic)
	Label    Label
	Category Category
}

// pool is a per-language set of realistic, non-builtin symbol names plus the
// call-site template that places a callee in a flaggable position.
type pool struct {
	lang     guard.Lang
	path     string
	symbols  []string // the "real" universe
	callLine func(sym string) string
}

// callLine templates put the symbol as a bare call target (before '('), which is
// the only position guard.ExtractRefs treats as a reference.
var pools = []pool{
	{
		// Go symbols are Exported (capitalized): RunEcho's IR indexes only
		// exported Go symbols, and the guard deliberately skips unexported refs
		// (extract.go), so an unexported pool would be entirely out of validation
		// scope — the benchmark would measure a non-feature. Go perturbations are
		// likewise kept exported (see perturb).
		lang: guard.LangGo, path: "synthetic.go",
		symbols: []string{
			"ParseConfig", "LoadManifest", "FetchUser", "RenderTemplate",
			"ValidateSchema", "ComputeRootHash", "OpenSnapshot", "EncodeRecord",
			"ResolveImports", "WalkSymbols", "BuildIndex", "DiffStructure",
		},
		callLine: func(s string) string { return "\t_ = " + s + "(ctx)" },
	},
	{
		lang: guard.LangJS, path: "synthetic.ts",
		symbols: []string{
			"parseConfig", "loadManifest", "fetchUser", "renderTemplate",
			"validateSchema", "serializeNode", "openSnapshot", "encodeRecord",
			"resolveImports", "walkSymbols", "buildIndex", "diffStructure",
		},
		callLine: func(s string) string { return "  const r = " + s + "(input);" },
	},
	{
		lang: guard.LangPython, path: "synthetic.py",
		symbols: []string{
			"parse_config", "load_manifest", "fetch_user", "render_template",
			"validate_schema", "compute_root_hash", "open_snapshot", "encode_record",
			"resolve_imports", "walk_symbols", "build_index", "diff_structure",
		},
		callLine: func(s string) string { return "    r = " + s + "(payload)" },
	},
}

// inventedBank holds plausible-but-absent helper names a model might confabulate.
// They are deliberately distinct from every pool symbol and from Go/JS/Py
// builtins, so an invented case is always a true unknown.
var inventedBank = []string{
	"flushCache", "retryWithBackoff", "normalizePath", "hydrateState",
	"deserializeBlob", "acquireLease", "rotateCredentials", "scheduleCompaction",
	"flush_cache", "retry_with_backoff", "normalize_path", "hydrate_state",
}

// Generate builds a deterministic, balanced corpus: perPool negatives and
// perPool positives (spread across perturbation categories) for each language.
// The same seed always yields the same cases.
func Generate(seed int64, perPool int) []Case {
	rng := rand.New(rand.NewSource(seed))
	var cases []Case

	for _, p := range pools {
		known := append([]string(nil), p.symbols...)
		sort.Strings(known)
		knownSet := make(map[string]struct{}, len(known))
		for _, s := range known {
			knownSet[s] = struct{}{}
		}

		// Negatives: call a real symbol.
		for i := 0; i < perPool; i++ {
			sym := p.symbols[rng.Intn(len(p.symbols))]
			cases = append(cases, Case{
				Lang: p.lang, Path: p.path, Line: p.callLine(sym),
				Symbol: sym, Known: known, Label: Real, Category: CatReal,
			})
		}

		// Positives: cycle through perturbation categories.
		cats := []Category{CatTypo, CatPlausibleAffix, CatWrongCase, CatInvented, CatRenamedAway}
		for i := 0; i < perPool; i++ {
			base := p.symbols[rng.Intn(len(p.symbols))]
			cat := cats[i%len(cats)]
			bad := perturb(rng, p.lang, cat, base, knownSet)
			if bad == "" {
				continue // perturbation collided with a real symbol; skip (rare)
			}
			cases = append(cases, Case{
				Lang: p.lang, Path: p.path, Line: p.callLine(bad),
				Symbol: bad, Known: known, Label: Hallucinated, Category: cat,
			})
		}
	}
	return cases
}

// perturb produces a hallucinated name guaranteed absent from knownSet, or ""
// if it could not (caller skips). Deterministic given rng state.
//
// For Go the result is forced to stay Exported (capitalized first rune): an
// unexported Go reference is out of the guard's validation scope by design, so a
// lowercase perturbation would be a guaranteed miss that says nothing about the
// guard. wrong_case for Go therefore flips an INTERIOR character (staying
// exported) rather than the first one.
func perturb(rng *rand.Rand, lang guard.Lang, cat Category, base string, knownSet map[string]struct{}) string {
	var cand string
	switch cat {
	case CatTypo:
		cand = dropOneChar(rng, base)
	case CatPlausibleAffix:
		affixes := []string{"File", "Sync", "Async", "V2", "Impl"}
		cand = base + affixes[rng.Intn(len(affixes))]
	case CatWrongCase:
		if lang == guard.LangGo {
			cand = flipInterior(rng, base) // keep exported, change interior case
		} else {
			cand = flipFirst(base)
		}
	case CatInvented:
		cand = inventedBank[rng.Intn(len(inventedBank))]
	case CatRenamedAway:
		prefixes := []string{"old", "legacy", "do", "raw"}
		cand = prefixes[rng.Intn(len(prefixes))] + capitalize(base)
	}
	if lang == guard.LangGo {
		cand = capitalize(cand) // hold every Go ref in the guard's exported scope
	}
	if _, exists := knownSet[cand]; exists || cand == base || cand == "" {
		return ""
	}
	return cand
}

func dropOneChar(rng *rand.Rand, s string) string {
	if len(s) < 4 {
		return ""
	}
	i := 1 + rng.Intn(len(s)-2) // never first/last char
	return s[:i] + s[i+1:]
}

func flipFirst(s string) string {
	if s == "" {
		return ""
	}
	c := s[0]
	switch {
	case c >= 'a' && c <= 'z':
		return string(c-32) + s[1:]
	case c >= 'A' && c <= 'Z':
		return string(c+32) + s[1:]
	}
	return ""
}

// flipInterior toggles the case of one interior letter (never the first), so an
// Exported Go name stays exported while still differing — a realistic mid-word
// case slip like ParseConfig -> ParseCOnfig.
func flipInterior(rng *rand.Rand, s string) string {
	if len(s) < 3 {
		return ""
	}
	i := 1 + rng.Intn(len(s)-1)
	c := s[i]
	switch {
	case c >= 'a' && c <= 'z':
		return s[:i] + string(c-32) + s[i+1:]
	case c >= 'A' && c <= 'Z':
		return s[:i] + string(c+32) + s[i+1:]
	}
	return ""
}

func capitalize(s string) string {
	if s == "" {
		return ""
	}
	if s[0] >= 'a' && s[0] <= 'z' {
		return string(s[0]-32) + s[1:]
	}
	return s
}
